version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "92:f2:6f:7a:1b:63:fa:5c:51:11:c9:96:64:b7:6a:ec"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/Tamari-Ba/deploy.sh"
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main